# Generated by Django 4.2.2 on 2023-06-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('data_nasc_cliente', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=50)),
                ('valor_unit_produto', models.FloatField()),
                ('marca_produto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id_carrinho', models.AutoField(primary_key=True, serialize=False)),
                ('qntd_produto', models.IntegerField()),
                ('valor_total_carrinho', models.FloatField(blank=True, null=True)),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicomercio.cliente')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicomercio.produto')),
            ],
        ),
    ]
